keycloak-realm: ${KEYCLOAK_REALM:https://auth.tennislichtenberg.de/realms/city-game}

spring:
  application:
    name: misterx
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-realm}
  jpa:
    open-in-view: false
  docker:
    compose:
      lifecycle-management: start_only

tenant:
  override:
    enabled: false

logging:
  level:
    root: warn
    net.lausi95.citygame: info
  include-application-group: false
  include-application-name: false

